# Generated by Django 4.2.2 on 2023-07-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodel",
            name="receiver_addr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="MessageModel_receiver_addr",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="sender_addr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
