# Generated by Django 4.2.2 on 2023-07-04 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendmodel",
            name="friend_req_receieved",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_friend_req_receieved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendmodel",
            name="friend_req_sent",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_friend_req_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendmodel",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
