# Generated by Django 4.2.2 on 2023-07-13 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="friendmodel", name="target_user",),
        migrations.AddField(
            model_name="friendmodel",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="FriendModel_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendmodel",
            name="request_status",
            field=models.CharField(
                blank=True, default="ACCEPTED", max_length=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="FriendRequestSentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_status",
                    models.CharField(
                        blank=True, default="PENDING", max_length=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender",
                    models.ManyToManyField(
                        blank=True,
                        related_name="FriendRequestSentModel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_status",
                    models.CharField(
                        blank=True, default="PENDING", max_length=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="FriendRequestModel_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
