# Generated by Django 4.2.2 on 2023-07-05 10:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="friendmodel", name="friend_req_receieved",),
        migrations.RemoveField(model_name="friendmodel", name="friend_req_sent",),
        migrations.RemoveField(model_name="friendmodel", name="friends",),
        migrations.AddField(
            model_name="friendmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendmodel",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "ACCEPTED"),
                    ("PENDING", "PENDING"),
                    ("REJECTED", "REJECTED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="friendmodel",
            name="target_user",
            field=models.ManyToManyField(
                blank=True,
                related_name="FriendModel_target_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
