# Generated by Django 4.2.2 on 2023-07-14 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0003_remove_friendmodel_target_user_friendmodel_friends_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="friendmodel", name="friends",),
        migrations.RemoveField(model_name="friendrequestmodel", name="requested_user",),
        migrations.RemoveField(model_name="friendrequestsentmodel", name="sender",),
        migrations.AddField(
            model_name="friendmodel",
            name="friends",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FriendModel_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendrequestmodel",
            name="requested_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FriendRequestModel_sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendrequestsentmodel",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="FriendRequestSentModel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
