# Generated by Django 4.2.2 on 2023-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_initial"),
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertisement",
                    models.ManyToManyField(
                        blank=True,
                        related_name="FeedModel_advertisement",
                        to="advertisement.advertisementsmodel",
                    ),
                ),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="FeedModel_posts",
                        to="posts.userpostmodel",
                    ),
                ),
            ],
        ),
    ]
