# Generated by Django 4.2.2 on 2023-07-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserEducationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edu_address",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPhoneNumberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_no", models.IntegerField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "MALE"), ("F", "FEMALE")], max_length=1
                    ),
                ),
                (
                    "user_profile_pic",
                    models.FileField(blank=True, null=True, upload_to="profile-image/"),
                ),
                (
                    "user_profile_bg_pic",
                    models.FileField(
                        blank=True, null=True, upload_to="profile-bg-image/"
                    ),
                ),
                ("user_bio", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_address",
                        to="userprofile.useraddressmodel",
                    ),
                ),
                (
                    "contact_no",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_contact_no",
                        to="userprofile.userphonenumbermodel",
                    ),
                ),
                (
                    "education_addr",
                    models.ManyToManyField(
                        blank=True, to="userprofile.usereducationmodel"
                    ),
                ),
                ("posts", models.ManyToManyField(blank=True, to="posts.userpostmodel")),
            ],
        ),
    ]
