# Generated by Django 4.2.2 on 2023-07-10 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        ("friends", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreUtils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.TextField(blank=True, max_length=100, null=True)),
                ("address2", models.TextField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserAddressModel_city",
                        to="coreUtils.citymodel",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserAddressModel_country",
                        to="coreUtils.countrymodel",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserAddressModel_state",
                        to="coreUtils.statemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserContactDetailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_no1", models.IntegerField(blank=True, null=True, unique=True)),
                ("mobile_no2", models.IntegerField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserEducationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college_edu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserEducationModel_college_edu",
                        to="coreUtils.collegeeducationmodel",
                    ),
                ),
                (
                    "higher_edu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserEducationModel_higer_edu",
                        to="coreUtils.highereducationaddressmodel",
                    ),
                ),
                (
                    "primay_edu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserEducationModel_primary_edu",
                        to="coreUtils.primaryeducationaddressmodel",
                    ),
                ),
                (
                    "secondary_edu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserEducationModel_secondary_edu",
                        to="coreUtils.secondaryeducationaddressmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "MALE"), ("F", "FEMALE")], max_length=1
                    ),
                ),
                (
                    "user_profile_pic",
                    models.FileField(blank=True, null=True, upload_to="profile-image/"),
                ),
                (
                    "user_profile_bg_pic",
                    models.FileField(
                        blank=True, null=True, upload_to="profile-bg-image/"
                    ),
                ),
                ("user_bio", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_address",
                        to="userprofile.useraddressmodel",
                    ),
                ),
                (
                    "contact_no",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_contact_no",
                        to="userprofile.usercontactdetailmodel",
                    ),
                ),
                (
                    "education_addr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserProfileModel_education_addr",
                        to="userprofile.usereducationmodel",
                    ),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_friend",
                        to="friends.friendmodel",
                    ),
                ),
                ("posts", models.ManyToManyField(blank=True, to="posts.userpostmodel")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserProfileModel_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workplace_addr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserProfileModel_workplace_addr",
                        to="coreUtils.employmentmodel",
                    ),
                ),
            ],
        ),
    ]
