# Generated by Django 4.2.2 on 2023-07-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("friends", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddressModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.TextField(blank=True, max_length=100, null=True)),
                ("address2", models.TextField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserContactDetailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_no1", models.IntegerField(blank=True, null=True, unique=True)),
                ("mobile_no2", models.IntegerField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserEducationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "MALE"), ("F", "FEMALE")], max_length=1
                    ),
                ),
                (
                    "user_profile_pic",
                    models.FileField(blank=True, null=True, upload_to="profile-image/"),
                ),
                (
                    "user_profile_bg_pic",
                    models.FileField(
                        blank=True, null=True, upload_to="profile-bg-image/"
                    ),
                ),
                ("user_bio", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_address",
                        to="userprofile.useraddressmodel",
                    ),
                ),
                (
                    "contact_no",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_contact_no",
                        to="userprofile.usercontactdetailmodel",
                    ),
                ),
                (
                    "education_addr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserProfileModel_education_addr",
                        to="userprofile.usereducationmodel",
                    ),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="UserProfileModel_friend",
                        to="friends.friendmodel",
                    ),
                ),
                ("posts", models.ManyToManyField(blank=True, to="posts.userpostmodel")),
            ],
        ),
    ]
