# Generated by Django 4.2.2 on 2023-07-11 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coreUtils", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserProfileModel_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="workplace_addr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserProfileModel_workplace_addr",
                to="coreUtils.employmentmodel",
            ),
        ),
        migrations.AddField(
            model_name="usereducationmodel",
            name="college_edu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserEducationModel_college_edu",
                to="coreUtils.collegeeducationmodel",
            ),
        ),
        migrations.AddField(
            model_name="usereducationmodel",
            name="higher_edu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserEducationModel_higer_edu",
                to="coreUtils.highereducationaddressmodel",
            ),
        ),
        migrations.AddField(
            model_name="usereducationmodel",
            name="primay_edu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserEducationModel_primary_edu",
                to="coreUtils.primaryeducationaddressmodel",
            ),
        ),
        migrations.AddField(
            model_name="usereducationmodel",
            name="secondary_edu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserEducationModel_secondary_edu",
                to="coreUtils.secondaryeducationaddressmodel",
            ),
        ),
        migrations.AddField(
            model_name="useraddressmodel",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserAddressModel_city",
                to="coreUtils.citymodel",
            ),
        ),
        migrations.AddField(
            model_name="useraddressmodel",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserAddressModel_country",
                to="coreUtils.countrymodel",
            ),
        ),
        migrations.AddField(
            model_name="useraddressmodel",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="UserAddressModel_state",
                to="coreUtils.statemodel",
            ),
        ),
    ]
