# Generated by Django 4.2.2 on 2023-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0003_remove_friendmodel_target_user_friendmodel_friends_and_more"),
        ("userprofile", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilemodel",
            name="friend_reqests_recieved",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_friend_reqests_received",
                to="friends.friendrequestmodel",
            ),
        ),
        migrations.AddField(
            model_name="userprofilemodel",
            name="friend_reqests_sent",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_friend_reqests_sent",
                to="friends.friendrequestsentmodel",
            ),
        ),
    ]
