# Generated by Django 4.2.2 on 2023-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0003_remove_friendmodel_friend_req_receieved_and_more"),
        ("userprofile", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilemodel",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="UserProfileModel_friend",
                to="friends.friendmodel",
            ),
        ),
    ]
